### ISSUE TITLE
Panic (addition overflow) when trying to unmarshalling ErrorIndication GTPU message

### ISSUE THREAD

**Issue by pventuzelo** [ErvinsK/gtp-rs#1]
We (@fuzzinglabs) found an overflow in gtp-rs making the library to crash:

```sh
thread 'main' panicked at 'attempt to add with overflow', /home/fuzzinglabs/gtp-rs/src/gtpv1/utils.rs:163:5
```

## Your Environment

- rustc 1.71.1 (eb26296b5 2023-08-03)
- Ubuntu 20.04

## Steps to reproduce

Download:

``` sh
git clone git@github.com:ErvinsK/gtp-rs.git
```

Testing program:

***main.rs***:

``` rust
use ::gtp_rs::gtpv1::gtpu::*;

fn main() {
    let mut buffer: Vec<u8> = vec![];
    let mut message = ErrorIndication::default();

    message.teid_data = Teid {
        t: 255,
        teid: 4294967295,
    };

    message.marshal(&mut buffer);
    let _result = ErrorIndication::unmarshal(&buffer);
}

```

***Cargo.toml***:

```
[package]
name = "gtp_rs_overflow"
version = "0.1.0"
edition = "2021"

[dependencies]
gtp-rs = { path = "gtp-rs" }

```

Build and run:

``` sh
cargo build
cargo run
```

## Root cause

https://github.com/ErvinsK/gtp-rs/blob/313f7af14053644f596746c19f91ecbfd05aaa02/src/gtpv1/utils.rs#L163
## Detailed behavior (RUST_BACKTRACE=1)

``` sh
thread 'main' panicked at 'attempt to add with overflow', /home/fuzzinglabs/gtp-rs/src/gtpv1/utils.rs:163:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:117:5
   3: gtp_rs::gtpv1::utils::check_tlv_ie_buffer
             at /home/fuzzinglabs/gtp-rs/src/gtpv1/utils.rs:163:5
   4: <gtp_rs::gtpv1::gtpu::messages::ies::privateextension::PrivateExtension as gtp_rs::gtpv1::gtpu::messages::ies::commons::IEs>::unmarshal
             at /home/fuzzinglabs/gtp-rs/src/gtpv1/gtpu/messages/ies/privateextension.rs:47:16
   5: <gtp_rs::gtpv1::gtpu::messages::errorindication::ErrorIndication as gtp_rs::gtpv1::gtpu::messages::commons::Messages>::unmarshal
             at /home/fuzzinglabs/gtp-rs/src/gtpv1/gtpu/messages/errorindication.rs:102:52
   6: gtp_rs_fuzzing::main
             at ./src/main.rs:13:19
   7: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ErvinsK** [comment]
Issue fixed with the latest commit - initial cause = loophole in overriding TEID type definition (setting type 255 instead of 16). Additional check implemented to eradicate the cause! Test are passing!
